export const DynamicPro = [
    {
    slug: "open-type-single-table-machine",
    name: "OPEN TYPE SINGLE TABLE MACHINE",
    category: "fiber-laser-cutting-machines",
    description: "Top edge sheet metal laser cutting, CE&ISO certified.",
    image: "/weldarcimg/1.webp",
    angleImg: [
      "/weldarcimg/1.webp",
      "/weldarcimg/1.webp",
      "/weldarcimg/1.webp",
    ],
    overView: [
      "With humanized design,and practical user experience.",
      "The flexible moving control system makes cutting more simply.",
      "German/Xy rack and pinion, rail from Taiwan Hiwin, servo motor from Japan Yaskawa makes the performance more stable.",
    ],
    ApplicableMaterials: [
      "Specially used for cutting carbon steel,stainless steel,galvanized steel,elctrolytic zinc-coated steel,silicon steel, brass and red copper and other kinds of thin metal sheets (material and thickness are related to laser type).",
    ],
    Specifications: [
      { name: "Model", data: "Fiber Cut - 1530" },
      { name: "Effective Cutting Width (mm)", data: "1500 x 3000" },
      { name: "Overall Size (mm)", data: "5020 x 3770 x 1650" },
      { name: "Total Weight (kg)", data: "4500" },
    ],
    TechnicalParameters: [
      { name: "Max. Cutting Speed", data: "100 m/min" },
      { name: "Max. Acceleration", data: "1.0 G" },
      { name: "X/Y Positioning Accuracy", data: "0.05 mm/m" },
      { name: "X/Y Repeated Positioning Accuracy", data: "±0.03 mm" },
      { name: "Operating Voltage", data: "415V/50Hz" },
      { name: "Laser Power", data: "500W-2000W" },
      { name: "Machine Running Temperature", data: "0°C-40°C" },
      { name: "Operating Voltage", data: "415V/50Hz" },
      { name: "Machine Running Humidity", data: "<90%" },
      { name: "Transmission", data: "Precise rack and pinion" },
    ],
    headers: ["W-1530", "W-2040", "W-2065", "W-2565"],
    rows: [
      {
        label: "Cutting range",
        values: ["1550×3150mm", "2000×4000mm", "2000×6500mm", "2500×6500mm"],
      },
      {
        label: "Laser power",
        values: [
          "1000W-12000W",
          "1000W-12000W",
          "1000W-12000W",
          "1000W-12000W",
        ],
      },
      {
        label: "Linkage speed",
        values: ["90m/min", "90m/min", "90m/min", "90m/min"],
      },
      {
        label: "Acceleration",
        values: ["1.5G", "1.5G", "1.5G", "1.5G"],
      },
      {
        label: "Positional accuracy",
        values: ["±0.03mm", "±0.03mm", "±0.03mm", "±0.03mm"],
      },
      {
        label: "Re-Positional accuracy",
        values: ["±0.02mm", "±0.02mm", "±0.02mm", "±0.02mm"],
      },
      {
        label: "Voltage",
        values: [
          "380-415V/50Hz 3Phase",
          "380-415V/50Hz 3Phase",
          "380-415V/50Hz 3Phase",
          "380-415V/50Hz 3Phase",
        ],
      },
    ],
  },
  {
    slug: "fiber-laser-with-exchangeable-table",
    name: "ENCLOSED EXCHANGABLE TABLE MACHINE",
    category: "fiber-laser-cutting-machines",
    description: "Top edge sheet metal laser cutting, CE&ISO certified.",
    image: "/weldarcimg/2.webp",
    angleImg: [
      "/weldarcimg/2.webp",
      "/weldarcimg/2.webp",
      "/weldarcimg/2.webp",
    ],
    overView: [
      "With humanized design,and practical user experience.",
      "The flexible moving control system makes cutting more simply.",
      "German/Xy rack and pinion, rail from Taiwan Hiwin, servo motor from Japan Yaskawa makes the performance more stable",
    ],
    ApplicableMaterials: [
      "Specially used for cutting carbon steel,stainless steel,galvanized steel,elctrolytic zinc-coated steel,silicon steel, brass and red copper and other kinds of thin metal sheets (material and thickness are related to laser type.",
    ],
    Specifications: [
      { name: "Model", data: "Fiber Cut - 1530" },
      { name: "Effective Cutting Width (mm)", data: "1500 x 3000" },
      { name: "Overall Size (mm)", data: "5020 x 3770 x 1650" },
      { name: "Total Weight (kg)", data: "4500" },
    ],
    TechnicalParameters: [
      { name: "Max. Cutting Speed", data: "100 m/min" },
      { name: "Max. Acceleration", data: "1.0 G" },
      { name: "X/Y Positioning Accuracy", data: "0.05 mm/m" },
      { name: "X/Y Repeated Positioning Accuracy", data: "±0.03 mm" },
      { name: "Operating Voltage", data: "415V/50Hz" },
      { name: "Laser Power", data: "500W-2000W" },
      { name: "Machine Running Temperature", data: "0°C-40°C" },
      { name: "Operating Voltage", data: "415V/50Hz" },
      { name: "Machine Running Humidity", data: "<90%" },
      { name: "Transmission", data: "Precise rack and pinion" },
    ],
    headers: ["W-1530", "W-2040", "W-2065", "W-2565"],
    rows: [
      {
        label: "Cutting range",
        values: ["1550×3150mm", "2000×4000mm", "2000×6500mm", "2500×6500mm"],
      },
      {
        label: "Laser power",
        values: [
          "1000W-12000W",
          "1000W-12000W",
          "1000W-12000W",
          "1000W-12000W",
        ],
      },
      {
        label: "Linkage speed",
        values: ["90m/min", "90m/min", "90m/min", "90m/min"],
      },
      {
        label: "Acceleration",
        values: ["1.5G", "1.5G", "1.5G", "1.5G"],
      },
      {
        label: "Positional accuracy",
        values: ["±0.03mm", "±0.03mm", "±0.03mm", "±0.03mm"],
      },
      {
        label: "Re-Positional accuracy",
        values: ["±0.02mm", "±0.02mm", "±0.02mm", "±0.02mm"],
      },
      {
        label: "Voltage",
        values: [
          "380-415V/50Hz 3Phase",
          "380-415V/50Hz 3Phase",
          "380-415V/50Hz 3Phase",
          "380-415V/50Hz 3Phase",
        ],
      },
    ],
  },
  {
    slug: "open-type-fiber-laser-cutting-machine",
    name: "OPEN TYPE FIBER LASER CUTTING MACHINE",
    category: "fiber-laser-cutting-machines",
    description: "Top edge sheet metal laser cutting, CE&ISO certified.",
    image: "/weldarcimg/4.webp",
    angleImg: [
      "/weldarcimg/4.webp",
      "/weldarcimg/2.webp",
      "/weldarcimg/2.webp",
    ],
    overView: [
      "With humanized design,and practical user experience.",
      "The flexible moving control system makes cutting more simply.",
      "German/Xy rack and pinion, rail from Taiwan Hiwin, servo motor from Japan Yaskawa makes the performance more stable.",
    ],
    ApplicableMaterials: [
      "Specially used for cutting carbon steel,stainless steel,galvanized steel,elctrolytic zinc-coated steel,silicon steel, brass and red copper and other kinds of thin metal sheets (material and thickness are related to laser type).",
    ],
    Specifications: [
      { name: "Model", data: "Fiber Cut - 1530" },
      { name: "Effective Cutting Width (mm)", data: "1500 x 3000" },
      { name: "Overall Size (mm)", data: "5020 x 3770 x 1650" },
      { name: "Total Weight (kg)", data: "4500" },
    ],
    TechnicalParameters: [
      { name: "Max. Cutting Speed", data: "100 m/min" },
      { name: "Max. Acceleration", data: "1.0 G" },
      { name: "X/Y Positioning Accuracy", data: "0.05 mm/m" },
      { name: "X/Y Repeated Positioning Accuracy", data: "±0.03 mm" },
      { name: "Operating Voltage", data: "415V/50Hz" },
      { name: "Laser Power", data: "500W-2000W" },
      { name: "Machine Running Temperature", data: "0°C-40°C" },
      { name: "Operating Voltage", data: "415V/50Hz" },
      { name: "Machine Running Humidity", data: "<90%" },
      { name: "Transmission", data: "Precise rack and pinion" },
    ],
    headers: ["W-1530", "W-2040", "W-2065", "W-2565"],
    rows: [
      {
        label: "Cutting range",
        values: ["1550×3150mm", "2000×4000mm", "2000×6500mm", "2500×6500mm"],
      },
      {
        label: "Laser power",
        values: [
          "1000W-12000W",
          "1000W-12000W",
          "1000W-12000W",
          "1000W-12000W",
        ],
      },
      {
        label: "Linkage speed",
        values: ["90m/min", "90m/min", "90m/min", "90m/min"],
      },
      {
        label: "Acceleration",
        values: ["1.5G", "1.5G", "1.5G", "1.5G"],
      },
      {
        label: "Positional accuracy",
        values: ["±0.03mm", "±0.03mm", "±0.03mm", "±0.03mm"],
      },
      {
        label: "Re-Positional accuracy",
        values: ["±0.02mm", "±0.02mm", "±0.02mm", "±0.02mm"],
      },
      {
        label: "Voltage",
        values: [
          "380-415V/50Hz 3Phase",
          "380-415V/50Hz 3Phase",
          "380-415V/50Hz 3Phase",
          "380-415V/50Hz 3Phase",
        ],
      },
    ],
  },
  {
    slug: "open-type-plates-&-pipes-fiber-laser-cutting-machine",
    name: "CNC FLAME/PLASMA CUTTING MACHINE",
    category: "fiber-laser-cutting-machines",
    description: "Top edge sheet metal laser cutting, CE&ISO certified.",
    image: "/weldarcimg/3.webp",
    angleImg: [
      "/weldarcimg/3.webp",
      "/weldarcimg/3.webp",
      "/weldarcimg/3.webp",
    ],
    overView: [
      "With humanized design,and practical user experience.",
      "The flexible moving control system makes cutting more simply.",
      "German/Xy rack and pinion, rail from Taiwan Hiwin, servo motor from Japan Yaskawa makes the performance more stable",
    ],
    ApplicableMaterials: [
      "Specially used for cutting carbon steel,stainless steel,galvanized steel,elctrolytic zinc-coated steel,silicon steel, brass and red copper and other kinds of thin metal sheets (material and thickness are related to laser type.",
    ],
    Specifications: [
      { name: "Model", data: "Fiber Cut - 1530" },
      { name: "Effective Cutting Width (mm)", data: "1500 x 3000" },
      { name: "Overall Size (mm)", data: "5020 x 3770 x 1650" },
      { name: "Total Weight (kg)", data: "4500" },
    ],
    TechnicalParameters: [
      { name: "Max. Cutting Speed", data: "100 m/min" },
      { name: "Max. Acceleration", data: "1.0 G" },
      { name: "X/Y Positioning Accuracy", data: "0.05 mm/m" },
      { name: "X/Y Repeated Positioning Accuracy", data: "±0.03 mm" },
      { name: "Operating Voltage", data: "415V/50Hz" },
      { name: "Laser Power", data: "500W-2000W" },
      { name: "Machine Running Temperature", data: "0°C-40°C" },
      { name: "Operating Voltage", data: "415V/50Hz" },
      { name: "Machine Running Humidity", data: "<90%" },
      { name: "Transmission", data: "Precise rack and pinion" },
    ],
    headers: ["WF-1530T", "WF-1545T", "WF-2040T", "WF-2060T", "WF-2560T"],
    rows: [
      {
        label: "Cutting range",
        values: [
          "1550×3150mm",
          "1500×4000mm",
          "2000×4000mm",
          "2000×6000mm",
          "2500×6000mm",
        ],
      },
      {
        label: "Laser power",
        values: [
          "1000W~6000W",
          "1000W~6000W",
          "1000W~6000W",
          "1000W~6000W",
          "1000W~6000W",
        ],
      },
      {
        label: "Linkage speed",
        values: ["90m/min", "90m/min", "90m/min", "90m/min", "90m/min"],
      },
      {
        label: "Acceleration",
        values: ["1.2G", "1.2G", "1.2G", "1.2G", "1.2G"],
      },
      {
        label: "Clamping range",
        values: [
          "T160: Ø",
          "T160: Ø",
          "-",
          "T240: Ø25~220mm",
          "T240: Ø25~220mm",
        ],
      },
      {
        label: "Processing Length of the pipe",
        values: ["3m/6.3m", "3m/6.3m", "3m/6.3m", "3m/6.3m", "3m/6.3m"],
      },
    ],
  },
  {
    slug: "h-beam-welding-machine-ptw",
    name: "H-Beam Welding Machine (PTW)",
    category: "h-beam-automation",
    description: "Top edge sheet metal laser cutting, CE&ISO certified.",
    image: "/weldarcimg/6.webp",
    angleImg: [
      "/weldarcimg/6.webp",
      "/weldarcimg/6.webp",
      "/weldarcimg/6.webp",
    ],
    overView: [
      "H-beam steel placed on workpiece support frame with 45째, which is suitable for boat welding.",
      "Gantry welding machine walks on rails at adjusted welding speed.",
      "Use SAW welding to weld two seam.",
      "Arc-guide frame automatic seam tracking.",
      "Flux automatic feed and recovery system",
    ],
    ApplicableMaterials: [
      "This automatic Gantry welding machine is mainly used for submerged arc welding of assembled H beam.",
    ],
    Specifications: [
      { name: "Model", data: "H-BEAM ASSEMBLY (HORIZONTAL) WELDING MACHINE" },
      { name: "Rail Gauge", data: "4000 mm" },
      { name: "Web Height", data: "2000 mm" },
      { name: "Flange width (Y)", data: "200-800mm" },
    ],
    TechnicalParameters: [
      { name: "Rail Gauge", data: "4000 mm" },
      { name: "Web Height", data: "2000 mm" },
      { name: "Flange width", data: "200-800mm" },
      { name: "Work-piece length", data: "4000-15000mm or as user's request" },
      { name: "Returninq speed", data: "0.15 m/1/min" },
    ],
  },
  {
    slug: "h-beam-welding-machine",
    name: "H-Beam Welding Machine",
    category: "h-beam-automation",
    description: "Top edge sheet metal laser cutting, CE&ISO certified.",
    image: "/weldarcimg/5.webp",
    angleImg: [
      "/weldarcimg/5.webp",
      "/weldarcimg/5.webp",
      "/weldarcimg/5.webp",
    ],
    overView: [
      "H-beam steel placed on workpiece support frame with 45째, which is suitable for boat welding.",
      "Gantry welding machine walks on rails at adjusted welding speed.",
      "Use SAW welding to weld two seam.",
      "Arc-guide frame automatic seam tracking.",
      "Flux automatic feed and recovery system",
    ],
    ApplicableMaterials: [
      "This automatic Gantry welding machine is mainly used for submerged arc welding of assembled H beam.",
    ],
    Specifications: [
      { name: "Model", data: "H-BEAM ASSEMBLY (HORIZONTAL) WELDING MACHINE" },
      { name: "Rail Gauge", data: "4000 mm" },
      { name: "Web Height", data: "2000 mm" },
      { name: "Flange width (Y)", data: "200-800mm" },
    ],
    TechnicalParameters: [
      { name: "Rail Gauge", data: "4000 mm" },
      { name: "Web Height", data: "2000 mm" },
      { name: "Flange width", data: "200-800mm" },
      { name: "Work-piece length", data: "4000-15000mm or as user's request" },
      { name: "Returninq speed", data: "0.15 m/1/min" },
    ],
  },
  {
    slug: "cnc-flame-plasma-cutting-machine-hypercut-4010",
    name: "CNC PLASMA FLAME CUTTING MACHINES",
    category: "cnc-plasma-flame-cutting-machines",
    description: "Top edge sheet metal laser cutting, CE&ISO certified.",
    image: "/weldarcimg/8.webp",
    angleImg: [
      "/weldarcimg/8.webp",
      "/weldarcimg/8.webp",
      "/weldarcimg/8.webp",
    ],
    overView: [
      "Quality Machine at Reasonable Price.",
      "Value for Money",
      "User-Friendly Controller",
      "Transverse and longitudinal Rack and Pinion.",
      "Drive for Accurate and Reliable Performance.",
    ],
    ApplicableMaterials: [
      "CNC plasma cutting machine is controlled by ADPS compared to ancient plasma cutting torch. The cutting is straight forward.This equipment is highly efficient, highly precise and highly reliable heat cutting machine, combining with the best mechanical drive and oxygen & plasma cutting technology, it is mainly used for profile cutting.",
    ],
    Specifications: [
      { name: "Model", data: "Hypercut-4010" },
      { name: "Effective Cutting Width (mm)", data: "1500 x 3000" },
      { name: "Overall Size (mm)", data: "5020 x 3770 x 1650" },
      { name: "Total Weight (kg)", data: "4500" },
    ],
    TechnicalParameters: [
      { name: "Track Width", data: "4000 mm" },
      { name: "Working Width", data: "3200 mm" },
      { name: "Over All Width", data: "4325 mm" },
      { name: "Over All Length", data: "10000 mm" },
      { name: "Working Length", data: "8500 mm" },
    ],
    headers: [
      "Model Name",
      "Track Width",
      "Working Width",
      "Over All Width",
      "Over All Length",
      "Working Length",
    ],
    rows: [
      {
        label: "SharpCut-2508",
        values: ["2500 mm", "1800 mm", "2700 mm", "8000 mm", "6500 mm"],
      },
      {
        label: "SharpCut-3008",
        values: ["3000 mm", "2000 mm", "3200 mm", "8500 mm", "7000 mm"],
      },
      {
        label: "SharpCut-3508",
        values: ["3500 mm", "2300 mm", "3700 mm", "9000 mm", "7500 mm"],
      },
      {
        label: "SharpCut-4008",
        values: ["4000 mm", "2600 mm", "4200 mm", "9500 mm", "8000 mm"],
      },
      {
        label: "SharpCut-4508",
        values: ["4500 mm", "2900 mm", "4700 mm", "10000 mm", "8500 mm"],
      },
    ],
  },
    {
    slug: "robotic-welding-hand-machine",
    name: "Robotic Welding Hand Machine",
    category: "h-beam-automation",
    description: "Top edge sheet metal laser cutting, CE&ISO certified.",
    image: "/weldarcimg/7.webp",
    angleImg: [
      "/weldarcimg/7.webp",
      "/weldarcimg/7.webp",
      "/weldarcimg/7.webp",
    ],
    overView: [
      "H-beam steel placed on workpiece support frame with 45째, which is suitable for boat welding.",
      "Gantry welding machine walks on rails at adjusted welding speed.",
      "Use SAW welding to weld two seam.",
      "Arc-guide frame automatic seam tracking.",
      "Flux automatic feed and recovery system",
    ],
    ApplicableMaterials: [
      "This automatic Gantry welding machine is mainly used for submerged arc welding of assembled H beam.",
    ],
    Specifications: [
      { name: "Model", data: "H-BEAM ASSEMBLY (HORIZONTAL) WELDING MACHINE" },
      { name: "Rail Gauge", data: "4000 mm" },
      { name: "Web Height", data: "2000 mm" },
      { name: "Flange width (Y)", data: "200-800mm" },
    ],
    TechnicalParameters: [
      { name: "Rail Gauge", data: "4000 mm" },
      { name: "Web Height", data: "2000 mm" },
      { name: "Flange width", data: "200-800mm" },
      { name: "Work-piece length", data: "4000-15000mm or as user's request" },
      { name: "Returninq speed", data: "0.15 m/1/min" },
    ],
  },
];
